version: "3"

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      - postgres
    environment:
      VIRTUAL_HOST: api.micro-twitter.quazarus.com
      VIRTUAL_PORT: 8080
      BUILD_NO: ${BUILD_NO}
      COMMIT: ${COMMIT}
    networks:
      - nginx-proxy
      - db

  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin123
    networks:
      - db

  test-reports:
    build:
      context: .
      dockerfile: test-reports.Dockerfile
    environment:
      VIRTUAL_HOST: test-reports.micro-twitter.quazarus.com
      VIRTUAL_PORT: 80
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  db:
