version: "3"

services:
  api:
    build:
      context: api
      dockerfile: deploy.Dockerfile
    depends_on:
      - postgresprod
    environment:
      VIRTUAL_HOST: api.micro-twitter.quazarus.com
      VIRTUAL_PORT: 8080
      BUILD_NO: ${BUILD_NO}
      COMMIT: ${COMMIT}
    networks:
      - nginx-proxy
      - db

  postgresprod:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: admin123
    networks:
      - db

  ui:
    build:
      context: ui
      dockerfile: deploy.Dockerfile
    depends_on:
      - api
    environment:
      VIRTUAL_HOST: micro-twitter.quazarus.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: micro-twitter.quazarus.com
      LETSENCRYPT_EMAIL: humberd.dev@gmail.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  db:

volumes:
  dbdata: