version: "3"

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - VIRTUAL_HOST: "api.micro-twitter.quazarus.com"
      - VIRTUAL_PORT: 8080
      - BUILD_NO: ${BUILD_NO}
      - COMMIT: ${COMMIT}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
